name: Actualizar Inventario Automático

on:
  push:
    branches:
      - main
    paths:
      - 'bitacora.csv'

jobs:
  actualizar-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar script de creación (Nuevos equipos)
        run: python py.py/Nuevo.py

      - name: Ejecutar script de actualización (Equipos existentes)
        run: python py.py/actualizar.py

      - name: Ejecutar script de eliminación (Eliminar equipos)
        run: python py.py/eliminar.py

      - name: Ejecutar script de devolución (Devolver a proveedor)
        run: python py.py/Devolver.py

      - name: Guardar inventarios en GitHub (Para la Web)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Servialco/*.csv AYS-Servialco/*.csv UNICAT/*.csv ARKY/*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualización automática de CSVs" && git push)

      - name: Sincronizar Bitácora con Excel (Google Sheets)
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          pip install gspread==5.12.4
          python py.py/actualizar_sheet.py
